### ISSUE TITLE
Kanban Board Set up

### ISSUE THREAD

**Issue by chiztechnology** [chiztechnology/rails-capstone-project#18]
## Hello dear reviewer 👋 

kindly find in this Issue the link to the Kanban board.

### Link to the project
Please find below the link to our team project as required at this phase of the project🔗
[Github Project](https://github.com/users/chiztechnology/projects/1).

### Member 👥
I'm the only member of this project since I've no coding partner this week.

@chiztechnology

**Comment by franclobo** [comment]
Hi @chiztechnology, 

![terminator](https://github.com/chiztechnology/rails-capstone-project/assets/58642949/b296e01e-5cef-429d-90a9-f9c8fc863b07)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, but the link to the kanban project is broken, it returns a 404 error.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by alexander16108** [comment]
Hi @chiztechnology,

<img src="https://media3.giphy.com/media/h4Hz4w9Jgrc1EY9VkL/giphy.gif"/>

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Invalid Code Review Request
You have submitted a project, but the link to the kanban project is broken, it returns a 404 error.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

Invalid Code Review Request does not count into the code reviews limit.

**Comment by chiztechnology** [comment]
Thank you for the feedback. it seems that my project visibility was set to private.
I just updated the visibility to public.

Looking forward to hearing from you!

**Comment by emmanuellekamwa** [comment]
**STATUS: APPROVED 🍾✔🎉**
Hello @franclobo 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- Descriptive PR.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
